In [1]:
from __future__ import print_function, division
#Allows relative imports
import os, sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
#imports from files
from src.preprocessing import *
from src.pickling import *
from src.torch_util import *
from src.repertoire_dataset import EmersonRepertoire_Dataset, load_train_test_repertoire
from vae_cel.DeepRC_VAE import *
from vae_cel.vae_cel import *

import pandas as pd 
import numpy as np
import math

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import BatchSampler, RandomSampler, SequentialSampler
#checking gpu status
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("Using : {}".format(device))
else:
    device = torch.device('cpu')
    print("Using : {}".format(device))
    
#Plot and stuff
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rcParams['figure.dpi']= 200
sns.set_style('darkgrid')


# Ignore warnings
import warnings
warnings.filterwarnings("ignore")
    
%load_ext autoreload
%autoreload 2

Using : cuda


In [3]:
x = pd.read_csv('../training_data_new/emerson_raw/batch1/emerson_batch1_train_top_20k.csv')

In [17]:
load_train_test_repertoire(datapath, 23, 100, 'B', 'B07', split_ratio = .7)


here ../training_data_new/emerson_raw/batch1/emerson_batch1_train_top_20k.csv
there 23 100
Here??
there???
how about this
here ../training_data_new/emerson_raw/batch1/emerson_batch1_test_top_20k.csv
there 23 100
Here??
there???
how about this
Splitting into train/val


(<src.repertoire_dataset.EmersonRepertoire_Dataset at 0x195f71b08b0>,
 <torch.utils.data.dataset.Subset at 0x195695e0490>)

In [5]:
datapath = '../training_data_new/emerson_raw/batch1/'
max_len = 23
top_k = 10000; allele = 'A'; pos_class = 'A01'; split_ratio = .6
train_dataset, test_dataset, train_subset, val_subset = load_train_test_repertoire(path = datapath,
                                                                                   max_len = max_len, top_k = top_k, allele = allele, 
                                                                                   pos_class = pos_class, split_ratio = split_ratio)

here ../training_data_new/emerson_raw/batch1/emerson_batch1_train_top_20k.csv
there 23 10000
here ../training_data_new/emerson_raw/batch1/emerson_batch1_test_top_20k.csv
there 23 10000


In [6]:
xd = torch.nn.BCELoss()

In [10]:
target = torch.randint(0,2,(10,))
target

tensor([0, 1, 1, 1, 1, 0, 1, 0, 1, 0])

In [12]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()

In [16]:
lin = nn.Linear(10,1)
x = torch.randn((4,10))
lin(x).flatten()

tensor([-0.2567, -0.2778,  0.1939,  0.0579], grad_fn=<ViewBackward>)

In [4]:
get_patient_topk_sequences(x, 10000)

filename        amino_acid  frequency  v_family  j_family  \
14386     HIP00110.tsv    CASSLTGMNTEAFF   0.000011         4         0   
18019     HIP00110.tsv   CASSLENRAAGSAFF   0.000012         4         0   
16879     HIP00110.tsv    CASSLVLGINEQFF   0.000012         4         1   
16856     HIP00110.tsv    CASGRTGLGYEQFF   0.000012         5         1   
16855     HIP00110.tsv      CASSNRVGEQFF   0.000012         9         1   
...                ...               ...        ...       ...       ...   
11215188  HIP19716.tsv  CASSSWGGPKDEKLFF   0.000023        24         0   
11215182  HIP19716.tsv  CASSRLALATYNEQFF   0.000023        13         1   
11211482  HIP19716.tsv  CASSQGTGTGANVLTF   0.000340         3         1   
11211480  HIP19716.tsv  CASSQEPGTGYSPLHF   0.000338         3         0   
11210147  HIP19716.tsv    CASSLSEILSPLHF   0.000015        10         0   

         hla_a1   hla_a2 hla_b1   hla_b2  
14386       A03      A24    B07  Unknown  
18019       A03      A24    B07  Unknown  
16879       A03      A24    B07  Unknown  
16856       A03      A24    B07  Unknown  
16855       A03      A24    B07  Unknown  
...         ...      ...    ...      ...  
11215188    A01  Unknown    B08  Unknown  
11215182    A01  Unknown    B08  Unknown  
11211482    A01  Unknown    B08  Unknown  
11211480    A01  Unknown    B08  Unknown  
11210147    A01  Unknown    B08  Unknown  

[5626686 rows x 9 columns]

In [11]:
from vae_cel.VAE_attention_trainers import *
pipeline_attention('../training_data_new/emerson_raw/batch1/',
                   10000, 'A', 'A01', .7,
         30, 1e-3, 4, name = 'testA01')


Using : cuda
Loading data, this may take a few minutes
Loading model
Model succesfully loaded from ../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/BEST_VAE_tune-weighted0.5_latent100_Pad-before_Annealing-hyper-gamma7.0.pth.tar:
	epoch: 49
Starting training
HERE C:\Users\richi\Documents\EPFL\Master\PDM\code\TREE\draft_notebooks


  0%|          | 0/3 [00:00<?, ?it/s]

Train Batch:   0%|          | 0/99 [00:00<?, ?it/s]

Valid Batch:   0%|          | 0/43 [00:00<?, ?it/s]

 loss at 0 epochs: TRAIN:6.666e-01,	 VAL:6.542e-01


Train Batch:   0%|          | 0/99 [00:00<?, ?it/s]

Valid Batch:   0%|          | 0/43 [00:00<?, ?it/s]

 loss at 1 epochs: TRAIN:6.377e-01,	 VAL:6.223e-01


Train Batch:   0%|          | 0/99 [00:00<?, ?it/s]

Valid Batch:   0%|          | 0/43 [00:00<?, ?it/s]

 loss at 2 epochs: TRAIN:6.115e-01,	 VAL:6.522e-01

Time elapsed:
	0.0 minutes
	43.201057 seconds


In [9]:
f = [x for x in os.listdir('../training_data_new/emerson_raw/batch1/') if 'emerson' in x and 'csv' in x]

In [14]:
f[0].split('.csv')

['emerson_batch1_test', '']

In [15]:
dir_ = '../training_data_new/emerson_raw/batch1/'
for x in f :
    
    tmp = get_patient_topk_sequences(pd.read_csv(dir_+x),
                               20000)
    fn = x.split('.csv')[0]+'top_20k.csv'
    tmp.to_csv(os.path.join(dir_, fn), header = True, index = False)

### check dataset


In [3]:
train_dataset, test_dataset, train, val = load_train_test_repertoire(path = '../training_data_new/emerson_raw/batch1/',
                                                                     max_len = 23, top_k = 10000, allele = 'A', 
                                                                     pos_class = 'A01', split_ratio = .7)

len(train_dataset), len(test_dataset), len(train), len(val)

(564, 62, 394, 170)

In [49]:
print(train.indices[4])
train_dataset[460][0] == train[4][0]
# getting Dataset[460] is equal to getting train[4] 
# because train[4] gives the index 460

460


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       ...,
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### check empty grad

In [77]:
class combined(nn.Module):
    
    def __init__(self, model1, model2):
        super(combined, self).__init__()
        self.mod1 = model1
        #self.mod1.requires_grad = False
        for p in self.mod1.parameters():
            p.requires_grad = False
        self.mod2 = model2
    def forward(self, x):
        x = self.mod1(x)
        x = self.mod2(x)
        return x 
mod1 = nn.Sequential(nn.Linear(10,20),
                     nn.ReLU(),
                     nn.Linear(20,20),
                     nn.SELU())

mod2 = nn.Sequential(nn.Linear(20,5), 
                     nn.ReLU(),
                     nn.Linear(5,2))

comb = combined(mod1,mod2)

In [84]:
xx = torch.randn((100,10))
yy = torch.randn((100,2))
crit = nn.MSELoss()
opt = torch.optim.SGD(comb.parameters(), lr = 1e-3)
out = comb(xx)

loss = crit(out,yy)
comb.zero_grad()
loss.backward()

In [85]:
comb.mod2[0].weight.grad, comb.mod1[2].weight.grad

(tensor([[-3.2112e-02,  6.6641e-03, -1.4971e-02,  5.8938e-03, -5.8211e-03,
          -1.5945e-02, -3.7710e-03, -6.7012e-04,  4.6982e-03, -1.3781e-02,
          -2.1570e-02, -5.9170e-03, -1.1678e-02, -2.9458e-03,  4.0377e-03,
          -1.5892e-02,  1.3305e-02,  9.4698e-03, -7.4193e-03,  8.1752e-04],
         [ 2.4865e-03,  7.5362e-04,  3.5638e-05, -6.5563e-04, -1.3543e-03,
           1.6707e-03, -7.4163e-05, -1.9239e-04, -7.9940e-04,  1.8660e-03,
           4.2817e-04, -1.0861e-03,  3.0768e-04, -5.2907e-04,  1.0264e-03,
           4.8657e-04,  2.2745e-03, -2.9416e-04, -1.6178e-03,  1.5655e-03],
         [ 2.7908e-03, -8.1720e-03,  2.9362e-03, -4.1228e-03,  4.1611e-03,
           5.5693e-04, -5.8695e-03,  4.3369e-03,  1.2786e-03, -6.4265e-03,
           1.8050e-03,  4.2103e-03,  2.9229e-03,  8.9660e-03, -4.9600e-04,
           4.6514e-03, -9.5777e-03, -6.9866e-03,  2.7985e-03, -7.0377e-03],
         [ 4.2767e-03, -5.3302e-03,  5.9997e-03,  1.6744e-03,  4.2696e-03,
          -3.9434e-03,

### train/val

#### VAE as embedder, with frozen VAE layers

In [3]:
from src.torch_util import *
VAE = VAE_cel(latent_dim = 100, aa_dim = 25)
path = '../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/'
VAE = load_model(VAE, os.path.join(path, [x for x in os.listdir(path) if 'best' in x.lower()][0]))

Model succesfully loaded from ../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/BEST_VAE_tune-weighted0.5_latent100_Pad-before_Annealing-hyper-gamma7.0.pth.tar:
	epoch: 49


In [23]:
from datetime import datetime as dt

def train_model(model, criterion, optimizer, dataset, train_subset, batch_size, 
                max_len, weighted, pad, positional, device):
    """trains for one full epoch (all batches)"""
    model.train()
    train_loss = 0
    for b in tqdm(BatchSampler(RandomSampler(train_subset), 
                          batch_size = batch_size, drop_last = False),
                  desc = 'Train Batch',
                  leave = False, position = 3):
        
        values, n_per_bag, target = dataset[b]
        target = torch.Tensor(target).to(device).long()
        x_tuple = batch_aa_vj(values, max_len, weighted, pad,
                              positional = True, atchley = False, device = device)
        
        output = model(x_tuple, n_per_bag)
        loss = criterion(output, target)
        model.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    train_loss /= math.floor(len(train_subset)/ batch_size)
    return train_loss

def eval_model(model, criterion, dataset, val_subset, batch_size, 
                max_len, weighted, pad, positional, device):
    """trains for one full epoch (all batches)"""
    model.eval()
    val_loss = 0
    for b in tqdm(BatchSampler(RandomSampler(val_subset), 
                          batch_size = batch_size, drop_last = False),
                  desc = 'Valid Batch',
                  leave = False, position=4):
        
        values, n_per_bag, target = dataset[b]
        target = torch.Tensor(target).to(device).long()
        x_tuple = batch_aa_vj(values, max_len, weighted, pad,
                              positional = True, atchley = False, device = device)
        
        output = model(x_tuple, n_per_bag)
        loss = criterion(output, target)
        val_loss += loss.item()
    val_loss /= math.floor(len(val_subset)/ batch_size)
    return val_loss

def train_attention(model, nb_epochs, lr, batch_size,
                    train_dataset, train_subset, val_subset, 
                    max_len=23, weighted=0.5, pad = 'before',
                    positional = True, device = 'cuda', name = ''):
    
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr = lr())
    train_losses = []
    val_losses = [] 
    best_val = 100
    
    model.to(device) 
    
    for e in tqdm(range(nb_epochs),
                  position=0, leave = False):
        train_loss = train_model(model,criterion, optimizer, train_dataset, train_subset,
                                 batch_size, max_len, weighted, pad, 
                                 positional, device)
        
        val_loss = eval_model(model, criterion, train_dataset, val_subset, batch_size, 
                              max_len, weighted, pad, positional, device)
        
        if e != 0 and val < best_val:
            torch.save({'state_dict':model.state_dict(), 'epoch':e, 'loss':val_loss}, 
                           f'./VAE_attention_{name}.pth.tar')
            best_val = val
            
        val_losses.append(val_losses)
        train_losses.append(train_losses)
        tqdm.write(f' loss at {e} epochs: TRAIN:{train_loss},\t VAL:{val_loss}')
        
    losses = {'train': train_losses,
              'val' : val_losses}
    return losses

def pipeline_attention(datapath, top_k, allele, pos_class, split_ratio, nb_epochs, lr, batch_size,
             max_len=23, weighted=0.5, pad = 'before',
             positional = True, device = 'cuda', name = ''):
    
    start_time = dt.now()
    print('Loading data, this may take a few minutes')
    train_dataset, test_dataset, train_subset, val_subset = load_train_test_repertoire(path = datapath,
                                                                                   max_len = max_len, top_k = top_k, allele = allele, 
                                                                                   pos_class = pos_class, split_ratio = split_ratio)
    #fixed model for now
    VAE = VAE_cel(latent_dim = 100, aa_dim = 25)
    path = '../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/'
    VAE = load_model(VAE, os.path.join(path, [x for x in os.listdir(path) if 'best' in x.lower()][0]))
    attention = AttentionNetwork(n_input_features = 100, n_layers = 3, n_units = 50)
    output_net = OutputNetwork(n_input_features = 100, n_output_features = 2,
                               n_layers = 2, n_units = 50)
    
    model = DeepRC_VAE(VAE,
                       attention,
                       output_net)
    
    losses = train_attention(model, nb_epochs, lr, batch_size,
                    train_dataset, train_subset, val_subset, 
                    max_len, weighted, pad,
                    positional, device, name)
    
    end_time = dt.now()       
    elapsed = divmod((end_time-start_time).total_seconds(), 60)
    print(f"\nTime elapsed:\n\t{elapsed[0]} minutes\n\t{elapsed[1]} seconds")
    return losses


In [22]:
pipeline_attention('../training_data_new/emerson_raw/batch1/', 10000, 'A', 'A01', .7,
         30, 1e-3, 4, name = 'testA01')

KeyboardInterrupt: 

In [2]:
train_dataset, test_dataset, train_subset, val_subset = load_train_test_repertoire(path = '../training_data_new/emerson_raw/batch1/',
                                                                                   max_len = 23, top_k = 10000, allele = 'A', 
                                                                                   pos_class = 'A01', split_ratio = .7)




In [10]:

VAE = VAE_cel(latent_dim = 100, aa_dim = 25)
path = '../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/'
VAE = load_model(VAE, os.path.join(path, [x for x in os.listdir(path) if 'best' in x.lower()][0]))
attention = AttentionNetwork(n_input_features = 100, n_layers = 3, n_units = 50)
output_net = OutputNetwork(n_input_features = 100, n_output_features = 2,
                           n_layers = 3, n_units = 50)

model = DeepRC_VAE(VAE,
                   attention,
                   output_net)
nb_epochs = 30
batch_size = 4 
lr = 1e-3
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr = lr)
train_losses = []
val_losses = [] 
best_val = 100
max_len = 23
weighted = 0.5

model.to(device) 

for e in tqdm(range(nb_epochs),position=0, leave = False):
    train_loss = train_model(model,criterion, optimizer, train_dataset, train_subset,
                             batch_size, max_len, weighted, pad='before', 
                             positional = True, device='cuda')
    
    val_loss = eval_model(model, criterion, train_dataset, val_subset, batch_size, 
                          max_len, weighted, 'before', True, device)
    
    if e != 0 and val < best_val:
        torch.save({'state_dict':model.state_dict(), 'epoch':e, 'loss':val_loss}, 
                       './deepRC_VAE_A01.pth.tar')
        best_val = val
        
    val_losses.append(val_losses)
    train_losses.append(train_losses)
    tqdm.write(f' loss at {e} epochs: TRAIN:{train_loss},\t VAL:{val_loss}')
    
losses = {'train': train_losses,
          'val' : val_losses}
#save_pkl('./withVAE_frozen_losses.pkl', losses)

Model succesfully loaded from ../output/HyperbolicTuning/LOWERBETA_gamma7_wd1e-3_ad3097/BEST_VAE_tune-weighted0.5_latent100_Pad-before_Annealing-hyper-gamma7.0.pth.tar:
	epoch: 49


  0%|          | 0/30 [00:00<?, ?it/s]

Train Batch:   0%|          | 0/99 [00:00<?, ?it/s]

Valid Batch:   0%|          | 0/43 [00:00<?, ?it/s]

NameError: name 'val' is not defined